export interface PersonalInvestmentResponse {
  code: 0 | -1,
  message: string,
  data: {
    id?: number,
    status?: unknown,
    discord?: string,
    farmId?: string,
    memberId?: unknown,
    doubleTaken?: boolean,
    investHcn?: number,
    volunteerHcn?: number,
    ttlQuata?: unknown,
    ico?: unknown,
    toFmv?: unknown,
    ifOn814?: unknown,
    kycEmail814?: unknown,
    id814?: unknown,
    reportConsistancy?: unknown,
    holdForOthers?: unknown,
    holdByOthers?: unknown,
    groupPFunc?: unknown,
    personalFund?: unknown,
    percent10?: unknown,
    lowerThan500?: unknown,
    suggesttedLockCoin?: unknown,
    idealAccountBal?: unknown,
    adjustmentForSuggestion?: unknown,
    idealAccountBalanceAfterLock?: unknown,
    actualEndBal?: unknown,
    diffOfLock?: unknown,
    lockStatus?: unknown,
    lockStatusForSCheck?: unknown,
    fmvTo920?: unknown,
    personalHoldingVsQuata?: unknown,
    bookRefKycEmail?: string,
    icoEmail?: string,
    updatedEmail?: string,
    blackList?: unknown,
    sinvestigation?: unknown
  }
}

export const regularUserDataNameMap: { [key: string]: string } = {
  discord: "Discord ID",
  farmId: "农场代号",
  memberId: "个人ID",
  investHcn: "",
  volunteerHcn: "投资理论应得币",
  ttlQuata: "总共理论应得币",
  ico: "上线后初始获得币",
  toFmv: "fmv锁币数量",
  kycEmail814: "8月14号的220表是否有邮件",
  id814: "8.14 是否有id",
  reportConsistancy: "申报是否真实",
  holdForOthers: "为他人持有数",
  holdByOthers: "被他人持有数",
  groupPFunc: "公司基金代持数",
  personalFund: "个人基金代持数",
  percent10: "10%释放数量",
  lowerThan500: "翻译数量", // ???
  suggesttedLockCoin: "建议锁币数量",
  idealAccountBal: "理论帐号喜币数量",
  adjustmentForSuggestion: "建议修改数量",
  idealAccountBalanceAfterLock: "锁币之后理想余额",
  actualEndBal: "实际锁币后差异",
  diffOfLock: "实际锁币后差异与理想锁币后余额之差",
  lockStatus: "多/少 锁币数量",
  lockStatusForSCheck: "锁币状态是否正常",
  fmvTo920: "9.20号锁币数量",
  personalHoldingVsQuata: "个人持有数量与quota的差异",
  bookRefKycEmail: "申报KYC采用邮件",
  icoEmail: "ico邮箱",
  updatedEmail: "更新后的邮箱",
  blackList: "是否黑名单",
  sinvestigation: "小sarah调查备注",
}